"use client";
import {ReactNode,useCallback,useEffect,useState} from "react";
import {api,CaseData,CaseDetail,jsonBody} from "../lib/api";
import Link from "next/link";
import CaseWorkspace from "./case-workspace";
import ReviewQueue from "./review-queue";
import CompanySettings, {SystemHealth} from "./company-settings";
import {useAuth} from "./auth-gate";
type Summary={cases:Record<string,number>;document_types:Record<string,number>;security:Record<string,number>;review_tasks:Record<string,number>};
type ListCase=CaseData&{document_types?:string[];security_states?:string[]};
const navigation=["Dashboard","Cases","Review Queue","Documents","System","Settings"];
const label=(s:string)=>s.replaceAll("_"," ");
function Status({value}:{value:string}){return <span className={`badge ${["READY","APPROVED","EXPORTED","SAFE"].includes(value)?"success":["FAILED","BLOCKED","QUARANTINED","SCAN_FAILED"].includes(value)?"danger":"warning"}`}>{label(value)}</span>;}
export default function AdminDashboard({legacy}:{legacy:ReactNode}){
  const {user,logout}=useAuth();
  const [view,setView]=useState("Dashboard");const [caseId,setCaseId]=useState("");const [summary,setSummary]=useState<Summary|null>(null);const [cases,setCases]=useState<ListCase[]>([]);const [error,setError]=useState("");const [loading,setLoading]=useState(true);const [query,setQuery]=useState("");const [status,setStatus]=useState("");const [offset,setOffset]=useState(0);const [total,setTotal]=useState(0);
  const load=useCallback(async()=>{const [s,c]=await Promise.all([api<Summary>("/documents/summary"),api<{items:ListCase[];total:number}>(`/cases?limit=25&offset=${offset}&q=${encodeURIComponent(query)}&status=${status}`)]);setSummary(s);setCases(c.items);setTotal(c.total);},[offset,query,status]);
  useEffect(()=>{let active=true;const timer=setTimeout(()=>{load().catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});},200);return()=>{active=false;clearTimeout(timer);};},[load]);
  useEffect(()=>{const timer=setTimeout(()=>{const id=new URLSearchParams(window.location.search).get("case");if(id){setCaseId(id);setView("Cases");}},0);return()=>clearTimeout(timer);},[]);
  useEffect(()=>{if(user.role==="ADMIN")void api<{configured:boolean}>("/settings/company").then(c=>{if(!c.configured)setView("Settings");}).catch(()=>{});},[user.role]);
  async function openCase(id:string){setCaseId(id);setView("Cases");}
  async function create(){setError("");try{const c=await api<CaseDetail>("/cases",{method:"POST",...jsonBody({})});await load();await openCase(c.id);}catch(e){setError(e instanceof Error?e.message:"Unable to create case");}}
  const counts=summary?.cases??{};const all=Object.values(counts).reduce((a,b)=>a+b,0);const quarantined=Object.entries(summary?.security??{}).filter(([k])=>["BLOCKED","QUARANTINED","SCAN_FAILED"].includes(k)).reduce((a,[,b])=>a+b,0);
  function caseTable(){return <div className="table-wrap"><table><thead><tr><th>Case / document</th><th>Customer</th><th>Type</th><th>Security</th><th>Status</th><th>Updated</th></tr></thead><tbody>{cases.map(c=><tr key={c.id}><td><button className="link case-link" onClick={()=>openCase(c.id)}>{c.request_title||"Untitled case"}</button><small className="mono">{c.public_id}</small></td><td>{c.company_name||c.customer_name||"Not assigned"}</td><td>{c.document_types?.map(label).join(", ")||"Unclassified / legacy"}</td><td>{c.security_states?.length?c.security_states.map(s=><Status key={s} value={s}/>):<span className="muted">No scan</span>}</td><td><Status value={c.status}/></td><td className="muted">{new Date(c.updated_at).toLocaleDateString()}</td></tr>)}</tbody></table>{!cases.length&&<div className="empty-state"><h3>No matching cases</h3><p>Create a case or adjust filters.</p></div>}</div>;}
  return <div className="admin-app"><aside className="sidebar"><Link className="brand" href="/"><span className="brand-mark">B</span><span>BOAH<small>DOCUMENT OPERATIONS</small></span></Link><p className="nav-label">WORKSPACE</p><nav aria-label="Main navigation">{navigation.filter(item=>user.role==="ADMIN"||!["Settings","System"].includes(item)).map((item,i)=><button key={item} aria-current={view===item?"page":undefined} className={view===item?"nav-active":""} onClick={()=>{setView(item);setCaseId("");void load().catch(e=>setError(e.message));}}><span className="nav-icon" aria-hidden>{["◫","▤","✓","▧","◉","⚙"][i]}</span>{item}{item==="Review Queue"&&<span className="nav-count">{summary?.review_tasks.OPEN??0}</span>}</button>)}</nav><div className="sidebar-footer"><span className="live-dot"/> Local workspace<small>Secure intake · Human oversight</small></div></aside>
    <main className="main-content"><header className="topbar"><div className="breadcrumb">Workspace <span>/</span> {view}{caseId&&" / Case detail"}</div><div className="operator"><span>OP</span><div>{user.email}<small>{user.role}</small></div><button className="secondary" onClick={logout}>Sign out</button></div></header><div className="page-content"><div className="page-heading"><div><p className="eyebrow">BUSINESS OPERATIONS AUTOMATION HUB</p><h1>{caseId?"Case workspace":view==="Dashboard"?"Operations overview":view}</h1><p className="muted">{view==="Dashboard"?"A clear view of documents, decisions and work that needs attention.":"Inspect the evidence. Resolve uncertainty. Keep every decision traceable."}</p></div><div className="toolbar">{caseId&&<button className="secondary" onClick={()=>setCaseId("")}>Back to cases</button>}{["ADMIN","OPERATOR"].includes(user.role)&&<button onClick={create}>＋ New case</button>}</div></div>
    {error&&<div role="alert" className="error-banner">{error}<button className="secondary" onClick={()=>{setError("");void load().catch(e=>setError(e.message));}}>Retry</button></div>}{loading?<div role="status" className="empty-state">Loading operations…</div>:<>
    {view==="Dashboard"&&<><div className="metrics-grid">{[["Total cases",all,"All intake channels"],["Ready for approval",counts.READY??0,"Business validation passed"],["Review required",counts.REVIEW_REQUIRED??0,"Operator attention needed"],["Security incidents",quarantined,"Blocked or quarantined scans"]].map(([name,value,hint])=><article className="metric-card" key={String(name)}><small>{name}</small><strong>{value}</strong><span>{hint}</span></article>)}</div><div className="dashboard-grid"><section className="panel"><div className="section-heading"><div><h2>Document distribution</h2><p className="muted">Classified documents across your workspace</p></div><span className="badge">Document types</span></div>{Object.entries(summary?.document_types??{}).length?Object.entries(summary!.document_types).map(([name,n])=><div className="distribution-row" key={name}><span>{label(name)}</span><progress value={n} max={Math.max(1,...Object.values(summary!.document_types))}/><strong>{n}</strong></div>):<p className="empty-state">Document types appear after secure intake.</p>}</section><section className="panel attention-card"><p className="eyebrow">HUMAN OVERSIGHT</p><h2>{summary?.review_tasks.OPEN??0} open review tasks</h2><p>Uncertain cells, unknown documents and security incidents stay visible until an operator resolves them.</p><button className="secondary" onClick={()=>setView("Review Queue")}>Open review queue →</button><div className="mini-stats"><span>Processing <strong>{counts.PROCESSING??0}</strong></span><span>Approved <strong>{(counts.APPROVED??0)+(counts.EXPORTED??0)}</strong></span></div></section></div><section className="panel"><div className="section-heading"><h2>Recent cases</h2><button className="link" onClick={()=>setView("Cases")}>View all cases →</button></div>{caseTable()}</section></>}
    {(view==="Cases"||view==="Documents")&&!caseId&&<section className="panel"><div className="filter-bar"><label>Search<input value={query} placeholder="Title, public ID or customer" onChange={e=>{setQuery(e.target.value);setOffset(0);}}/></label><label>Status<select value={status} onChange={e=>{setStatus(e.target.value);setOffset(0);}}><option value="">All statuses</option>{["RECEIVED","PROCESSING","REVIEW_REQUIRED","READY","APPROVED","EXPORTED","FAILED"].map(s=><option key={s}>{s}</option>)}</select></label><span className="muted">{total} matching cases</span></div>{caseTable()}<div className="toolbar pagination"><button className="secondary" disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-25))}>Previous</button><span>{Math.min(offset+1,total)}–{Math.min(offset+25,total)} / {total}</span><button className="secondary" disabled={offset+25>=total} onClick={()=>setOffset(offset+25)}>Next</button></div></section>}
    {caseId&&<CaseWorkspace key={caseId} initialCaseId={caseId}/>}{view==="Review Queue"&&<ReviewQueue onCase={openCase} navigateOnSelect={false}/>}
    {view==="Settings"&&<CompanySettings/>}{view==="System"&&<><SystemHealth/><details className="panel"><summary>Compatibility workspace (M1–M5)</summary>{legacy}</details></>}
    </>}<footer className="app-footer">BOAH · Document operations workspace <span>Local processing. Auditable decisions.</span></footer></div></main></div>;
}
