"use client";
import {useState} from "react";
import Image from "next/image";
import {AdaptiveDocument, CaseDetail, API_BASE, api, jsonBody} from "../lib/api";

export default function DocumentPanel({document,editable,onReviewed}:{document:AdaptiveDocument;caseId:string;editable:boolean;onReviewed:(c:CaseDetail)=>void}) {
  const [values,setValues]=useState<Record<string,string>>({});const [reason,setReason]=useState("");
  const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [page,setPage]=useState(1);const [previewFailed,setPreviewFailed]=useState(false);
  const cells=document.tables.flatMap(t=>t.cells);
  async function review(){setBusy(true);setError("");try{onReviewed(await api<CaseDetail>(`/documents/${document.id}/review`,{method:"POST",...jsonBody({revision:document.revision,reason,cells:cells.map(c=>({cell_id:c.id,value:values[c.id]??c.corrected_value??c.raw_value??""}))})}));setValues({});setReason("");}catch(e){setError(e instanceof Error?e.message:"Review failed");}finally{setBusy(false);}}
  return <section className="panel document-panel"><div className="section-heading"><div><p className="eyebrow">DOCUMENT INTELLIGENCE</p><h2>{document.document_type.replaceAll("_"," ")}</h2></div><span className={`badge ${document.reviewed?"success":"warning"}`}>{document.reviewed?"Human verified":document.review_required?"Review required":"Invoice pipeline"}</span></div>
    <div className="document-meta"><div><small>Classification confidence</small><strong>{Math.round(document.confidence*100)}%</strong></div><div><small>Extraction route</small><strong>{document.strategy.replaceAll("-"," ")}</strong></div><div><small>Cells awaiting confirmation</small><strong>{cells.filter(c=>c.uncertain&&c.corrected_value===null).length}</strong></div></div><p className="muted">{document.reasons.join(" · ")}</p>
    <div className="document-layout"><div className="original-preview"><div className="toolbar"><h3>Original document</h3><label>Page<select value={page} onChange={e=>{setPage(Number(e.target.value));setPreviewFailed(false);}}>{(document.pages.length?document.pages:[{page:1}]).map(p=><option key={p.page} value={p.page}>{p.page}</option>)}</select></label></div>
      {!previewFailed?<Image unoptimized width={780} height={1040} src={`${API_BASE}/documents/${document.id}/preview?page=${page}`} alt={`Original document page ${page}`} onError={()=>setPreviewFailed(true)} className="document-image"/>:<p className="empty-state">Preview unavailable. Inspect the stored SAFE original or extracted text.</p>}
    </div><div className="extraction-panel"><h3>{document.tables.length?"Structured table extraction":"Document content"}</h3>{!document.tables.length&&<pre className="readable-text">{document.raw_text||"No reliable text extracted. Human inspection required."}</pre>}
      {document.tables.map((table,ti)=><div className="table-editor" key={table.id}><div className="toolbar"><strong>Table {ti+1}</strong><span className="muted">Page {table.page} · {table.row_count} × {table.column_count}</span></div>{table.irregular&&<p className="warning-note">Irregular or merged regions detected. Verify structure against the original.</p>}<div className="table-wrap"><table><tbody>{Array.from({length:table.row_count},(_,row)=><tr key={row}>{Array.from({length:table.column_count},(_,col)=>{const cell=table.cells.find(c=>c.row===row&&c.column===col);if(!cell)return <td key={col}>Unresolved region</td>;const uncertain=cell.uncertain&&cell.corrected_value===null;return <td key={cell.id} className={`${row===0?"header-cell":""} ${uncertain?"uncertain-cell":""}`}><input aria-label={`Table ${ti+1} row ${row+1} column ${col+1}`} disabled={!editable||busy} value={values[cell.id]??cell.corrected_value??cell.raw_value??""} placeholder={uncertain?"Confirm value":"Empty"} onChange={e=>setValues({...values,[cell.id]:e.target.value})}/><small>{cell.corrected_value!==null?"Human verified":uncertain?"Needs confirmation":`${Math.round(cell.confidence*100)}% · ${cell.source}`}</small></td>;})}</tr>)}</tbody></table></div>{table.issues.map((issue,i)=><p className="error" key={i}>{issue.row!==undefined?`Row ${issue.row+1}: `:""}{issue.message}</p>)}</div>)}
      {document.document_type==="HANDWRITTEN_TABLE"&&<p className="warning-note">Unrecognized handwriting is left empty. Review every cell against the original; submitted blanks are explicit human confirmations.</p>}
      {editable&&document.document_type!=="INVOICE"&&<form onSubmit={e=>{e.preventDefault();void review();}} className="review-form"><label>Review reason<textarea value={reason} maxLength={2000} onChange={e=>setReason(e.target.value)} placeholder="Describe the original checked and corrections made"/></label><button disabled={busy||!reason.trim()}>{busy?"Validating…":"Confirm document & validate"}</button></form>}{error&&<p role="alert" className="error">{error}</p>}
    </div></div></section>;
}
