"""company setup identities connectors routing and operations

Revision ID: 2836cf000b0e
Revises: ad14d3ede9c3
Create Date: 2026-09-29 13:00:20.267875
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2836cf000b0e"
down_revision: str | Sequence[str] | None = "ad14d3ede9c3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_name", sa.String(length=255), nullable=False),
        sa.Column("identifier", sa.String(length=80), nullable=True),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("locale", sa.String(length=20), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("notification_email", sa.String(length=320), nullable=True),
        sa.Column("notifications", sa.JSON(), nullable=False),
        sa.Column("retention", sa.JSON(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "login_throttles",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("failures", sa.Integer(), nullable=False),
        sa.Column("window_started", sa.DateTime(timezone=True), nullable=False),
        sa.Column("blocked_until", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "routing_rules",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("document_type", sa.String(length=32), nullable=False),
        sa.Column("case_state", sa.String(length=20), nullable=False),
        sa.Column("require_reviewed", sa.Boolean(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "secrets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("nonce", sa.LargeBinary(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "system_audit",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event", sa.String(length=64), nullable=False),
        sa.Column("actor", sa.String(length=80), nullable=False),
        sa.Column("target", sa.String(length=100), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_system_audit_event"), "system_audit", ["event"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("failed_logins", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "worker_heartbeats",
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "document_sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("secret_id", sa.Uuid(), nullable=True),
        sa.Column("runtime_state", sa.JSON(), nullable=False),
        sa.Column("interval_seconds", sa.Integer(), nullable=False),
        sa.Column("next_poll_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=200), nullable=True),
        sa.Column("last_message", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.ForeignKeyConstraint(
            ["secret_id"],
            ["secrets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "output_destinations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("secret_id", sa.Uuid(), nullable=True),
        sa.Column("last_success", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=200), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.ForeignKeyConstraint(
            ["secret_id"],
            ["secrets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "retention_deletions",
        sa.Column("storage_key", sa.String(length=1024), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("artifact_kind", sa.String(length=30), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.PrimaryKeyConstraint("storage_key"),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("csrf_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_table(
        "delivery_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=True),
        sa.Column("destination_id", sa.Uuid(), nullable=True),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("artifacts", sa.JSON(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.String(length=200), nullable=True),
        sa.Column("next_retry", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["destination_id"],
            ["output_destinations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["document_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(op.f("ix_delivery_jobs_case_id"), "delivery_jobs", ["case_id"], unique=False)
    op.create_index(op.f("ix_delivery_jobs_status"), "delivery_jobs", ["status"], unique=False)
    op.create_table(
        "rule_destinations",
        sa.Column("rule_id", sa.Uuid(), nullable=False),
        sa.Column("destination_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["destination_id"],
            ["output_destinations.id"],
        ),
        sa.ForeignKeyConstraint(["rule_id"], ["routing_rules.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("rule_id", "destination_id"),
    )
    op.create_table(
        "source_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("identity", sa.String(length=128), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["document_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "identity", name="uq_source_item"),
    )
    with op.batch_alter_table("review_tasks") as batch:
        batch.drop_constraint("ck_task_type", type_="check")
        batch.create_check_constraint(
            "ck_task_type",
            "task_type IN ('SECURITY_QUARANTINE','OCR_REVIEW',"
            "'EXTRACTION_FAILURE','UNSUPPORTED_ATTACHMENT','DOCUMENT_REVIEW','INTEGRATION_FAILURE')",
        )


def downgrade() -> None:
    # Preserve historical operational evidence under the earlier generic category.
    op.execute(
        "UPDATE review_tasks SET task_type='EXTRACTION_FAILURE' "
        "WHERE task_type='INTEGRATION_FAILURE'"
    )
    with op.batch_alter_table("review_tasks") as batch:
        batch.drop_constraint("ck_task_type", type_="check")
        batch.create_check_constraint(
            "ck_task_type",
            "task_type IN ('SECURITY_QUARANTINE','OCR_REVIEW',"
            "'EXTRACTION_FAILURE','UNSUPPORTED_ATTACHMENT','DOCUMENT_REVIEW')",
        )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("source_items")
    op.drop_table("rule_destinations")
    op.drop_index(op.f("ix_delivery_jobs_status"), table_name="delivery_jobs")
    op.drop_index(op.f("ix_delivery_jobs_case_id"), table_name="delivery_jobs")
    op.drop_table("delivery_jobs")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_table("retention_deletions")
    op.drop_table("output_destinations")
    op.drop_table("document_sources")
    op.drop_table("worker_heartbeats")
    op.drop_table("users")
    op.drop_index(op.f("ix_system_audit_event"), table_name="system_audit")
    op.drop_table("system_audit")
    op.drop_table("secrets")
    op.drop_table("routing_rules")
    op.drop_table("login_throttles")
    op.drop_table("company_settings")
    # ### end Alembic commands ###
