"""secure intake review tasks and notification outbox

Revision ID: 59bc8877f30b
Revises: f3a901c2d700
Create Date: 2026-09-28 14:47:40.927883
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "59bc8877f30b"
down_revision: str | Sequence[str] | None = "f3a901c2d700"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_receipts",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_table(
        "attachment_security_scans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("attachment_id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("verdict", sa.String(length=20), nullable=False),
        sa.Column("scanner", sa.String(length=64), nullable=False),
        sa.Column("scanner_version", sa.String(length=255), nullable=True),
        sa.Column("detected_mime", sa.String(length=255), nullable=True),
        sa.Column("claimed_mime", sa.String(length=255), nullable=True),
        sa.Column("extension", sa.String(length=32), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("checks", sa.JSON(), nullable=False),
        sa.Column("threat_name", sa.Text(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "verdict IN ('PENDING','SAFE','QUARANTINED','BLOCKED','SCAN_FAILED')",
            name="ck_security_verdict",
        ),
        sa.CheckConstraint("size_bytes >= 0", name="ck_scan_size"),
        sa.ForeignKeyConstraint(["attachment_id"], ["attachments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_attachment_security_scans_attachment_id"),
        "attachment_security_scans",
        ["attachment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attachment_security_scans_case_id"),
        "attachment_security_scans",
        ["case_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attachment_security_scans_verdict"),
        "attachment_security_scans",
        ["verdict"],
        unique=False,
    )
    op.create_table(
        "review_tasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("attachment_id", sa.Uuid(), nullable=True),
        sa.Column("active_key", sa.String(length=255), nullable=True),
        sa.Column("task_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("priority", sa.String(length=16), nullable=False),
        sa.Column("reason_code", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("assigned_to", sa.String(length=128), nullable=True),
        sa.CheckConstraint("priority IN ('CRITICAL','HIGH','NORMAL')", name="ck_task_priority"),
        sa.CheckConstraint(
            "status IN ('OPEN','ACKNOWLEDGED','RESOLVED','DISMISSED')", name="ck_task_status"
        ),
        sa.CheckConstraint(
            "task_type IN ('SECURITY_QUARANTINE','OCR_REVIEW',"
            "'EXTRACTION_FAILURE','UNSUPPORTED_ATTACHMENT')",
            name="ck_task_type",
        ),
        sa.ForeignKeyConstraint(
            ["attachment_id"],
            ["attachments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("active_key"),
    )
    op.create_index(op.f("ix_review_tasks_case_id"), "review_tasks", ["case_id"], unique=False)
    op.create_index(op.f("ix_review_tasks_priority"), "review_tasks", ["priority"], unique=False)
    op.create_index(op.f("ix_review_tasks_status"), "review_tasks", ["status"], unique=False)
    op.create_index(op.f("ix_review_tasks_task_type"), "review_tasks", ["task_type"], unique=False)
    op.create_table(
        "notification_outbox",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["review_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_id"),
    )
    op.create_index(
        op.f("ix_notification_outbox_case_id"), "notification_outbox", ["case_id"], unique=False
    )
    op.create_index(
        op.f("ix_notification_outbox_next_attempt_at"),
        "notification_outbox",
        ["next_attempt_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_outbox_sent_at"), "notification_outbox", ["sent_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notification_outbox_sent_at"), table_name="notification_outbox")
    op.drop_index(op.f("ix_notification_outbox_next_attempt_at"), table_name="notification_outbox")
    op.drop_index(op.f("ix_notification_outbox_case_id"), table_name="notification_outbox")
    op.drop_table("notification_outbox")
    op.drop_index(op.f("ix_review_tasks_task_type"), table_name="review_tasks")
    op.drop_index(op.f("ix_review_tasks_status"), table_name="review_tasks")
    op.drop_index(op.f("ix_review_tasks_priority"), table_name="review_tasks")
    op.drop_index(op.f("ix_review_tasks_case_id"), table_name="review_tasks")
    op.drop_table("review_tasks")
    op.drop_index(
        op.f("ix_attachment_security_scans_verdict"), table_name="attachment_security_scans"
    )
    op.drop_index(
        op.f("ix_attachment_security_scans_case_id"), table_name="attachment_security_scans"
    )
    op.drop_index(
        op.f("ix_attachment_security_scans_attachment_id"), table_name="attachment_security_scans"
    )
    op.drop_table("attachment_security_scans")
    op.drop_table("notification_receipts")
    # ### end Alembic commands ###
