"""document classification structured tables and corrections

Revision ID: ad14d3ede9c3
Revises: 59bc8877f30b
Create Date: 2026-09-28 19:51:13.010142
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "ad14d3ede9c3"
down_revision: str | Sequence[str] | None = "59bc8877f30b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.drop_constraint("ck_task_type", "review_tasks", type_="check")
    op.create_check_constraint(
        "ck_task_type",
        "review_tasks",
        "task_type IN ('SECURITY_QUARANTINE','OCR_REVIEW','EXTRACTION_FAILURE',"
        "'UNSUPPORTED_ATTACHMENT','DOCUMENT_REVIEW')",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_analyses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("attachment_id", sa.Uuid(), nullable=False),
        sa.Column("document_type", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("classifier", sa.String(length=64), nullable=False),
        sa.Column("reasons", sa.JSON(), nullable=False),
        sa.Column("pages", sa.JSON(), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("artifacts", sa.JSON(), nullable=False),
        sa.Column("strategy", sa.String(length=64), nullable=False),
        sa.Column("review_required", sa.Boolean(), nullable=False),
        sa.Column("reviewed", sa.Boolean(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "document_type IN ('INVOICE','HANDWRITTEN_TABLE','PRINTED_TABLE',"
            "'GENERIC_DOCUMENT','UNKNOWN')",
            name="ck_document_type",
        ),
        sa.CheckConstraint("confidence >= 0 AND confidence <= 1", name="ck_class_conf"),
        sa.ForeignKeyConstraint(
            ["attachment_id"],
            ["attachments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("attachment_id"),
    )
    op.create_index(
        op.f("ix_document_analyses_case_id"), "document_analyses", ["case_id"], unique=False
    )
    op.create_index(
        op.f("ix_document_analyses_document_type"),
        "document_analyses",
        ["document_type"],
        unique=False,
    )
    op.create_table(
        "document_corrections",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("changes", sa.JSON(), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document_analyses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_document_corrections_document_id"),
        "document_corrections",
        ["document_id"],
        unique=False,
    )
    op.create_table(
        "document_tables",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("page", sa.Integer(), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("column_count", sa.Integer(), nullable=False),
        sa.Column("bbox", sa.JSON(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("irregular", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document_analyses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_document_tables_document_id"), "document_tables", ["document_id"], unique=False
    )
    op.create_table(
        "document_cells",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("table_id", sa.Uuid(), nullable=False),
        sa.Column("row", sa.Integer(), nullable=False),
        sa.Column("column", sa.Integer(), nullable=False),
        sa.Column("raw_value", sa.Text(), nullable=True),
        sa.Column("corrected_value", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("bbox", sa.JSON(), nullable=True),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("uncertain", sa.Boolean(), nullable=False),
        sa.CheckConstraint("confidence >= 0 AND confidence <= 1", name="ck_cell_conf"),
        sa.ForeignKeyConstraint(
            ["table_id"],
            ["document_tables.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("table_id", "row", "column", name="uq_table_cell"),
    )
    op.create_index(
        op.f("ix_document_cells_table_id"), "document_cells", ["table_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("UPDATE review_tasks SET task_type='OCR_REVIEW' WHERE task_type='DOCUMENT_REVIEW'")
    op.drop_constraint("ck_task_type", "review_tasks", type_="check")
    op.create_check_constraint(
        "ck_task_type",
        "review_tasks",
        "task_type IN ('SECURITY_QUARANTINE','OCR_REVIEW','EXTRACTION_FAILURE',"
        "'UNSUPPORTED_ATTACHMENT')",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_document_cells_table_id"), table_name="document_cells")
    op.drop_table("document_cells")
    op.drop_index(op.f("ix_document_tables_document_id"), table_name="document_tables")
    op.drop_table("document_tables")
    op.drop_index(op.f("ix_document_corrections_document_id"), table_name="document_corrections")
    op.drop_table("document_corrections")
    op.drop_index(op.f("ix_document_analyses_document_type"), table_name="document_analyses")
    op.drop_index(op.f("ix_document_analyses_case_id"), table_name="document_analyses")
    op.drop_table("document_analyses")
    # ### end Alembic commands ###
