"""inbound email identity and source

Revision ID: e5ebcbe7c468
Revises: 72087185dc49
Create Date: 2026-09-27 12:07:00.539784
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "e5ebcbe7c468"
down_revision: str | Sequence[str] | None = "72087185dc49"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inbound_messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("external_message_id", sa.String(length=998), nullable=True),
        sa.Column("identity_key", sa.String(length=64), nullable=False),
        sa.Column("identity_method", sa.String(length=32), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=True),
        sa.Column("sender_address", sa.String(length=320), nullable=False),
        sa.Column("sender_name", sa.String(length=255), nullable=True),
        sa.Column("recipients", sa.JSON(), nullable=False),
        sa.Column("cc", sa.JSON(), nullable=False),
        sa.Column("reply_to", sa.JSON(), nullable=False),
        sa.Column("subject", sa.String(length=998), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("text_body", sa.Text(), nullable=False),
        sa.Column("html_body", sa.Text(), nullable=True),
        sa.Column("processing_status", sa.String(length=32), nullable=False),
        sa.Column("attachment_results", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id"),
        sa.UniqueConstraint("source_type", "identity_key", name="uq_inbound_source_identity"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("inbound_messages")
    # ### end Alembic commands ###
